import type { HubOrder } from "./types";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3_600_000).toISOString();

export const INITIAL_ORDERS: HubOrder[] = [
  // ── Unassigned (Assign page) ──────────────────────────────────────────
  {
    id: "TT-45829",
    platform: "tiktok",
    createdAt: hoursAgo(5),
    customer: "@user_isabela",
    product: "Faja Shapewear Curve Pro",
    sku: "FTC-SH-014",
    qty: 1,
    status: "unassigned",
    invoiceStatus: "none",
    labelStatus: "none",
    activity: [{ time: hoursAgo(5), text: "Orden importada desde TikTok Shop." }],
  },
  {
    id: "AMZ-718392",
    platform: "amazon",
    createdAt: hoursAgo(14),
    customer: "M. Rodriguez",
    product: "Waist Trainer Classic Black",
    sku: "FTC-WT-002",
    qty: 2,
    status: "unassigned",
    invoiceStatus: "none",
    labelStatus: "none",
    activity: [{ time: hoursAgo(14), text: "Orden detectada en Shopify (Unfulfilled, Source: Amazon)." }],
  },
  {
    id: "SHO-3391",
    platform: "shopify",
    createdAt: hoursAgo(21),
    customer: "Andrea Gómez",
    product: "Faja Post Quirúrgica Etapa 2",
    sku: "FTC-PQ-021",
    qty: 1,
    status: "unassigned",
    invoiceStatus: "none",
    labelStatus: "none",
    activity: [{ time: hoursAgo(21), text: "Orden online importada desde Shopify (Unfulfilled)." }],
  },
  {
    id: "TT-45840",
    platform: "tiktok",
    createdAt: hoursAgo(2),
    customer: "@user_valeria22",
    product: "Body Reductor Manga Larga",
    sku: "FTC-BR-009",
    qty: 1,
    status: "unassigned",
    invoiceStatus: "none",
    labelStatus: "none",
    activity: [{ time: hoursAgo(2), text: "Orden importada desde TikTok Shop." }],
  },

  // ── Pending Logistics (assigned, needs invoice/label work) ────────────
  {
    id: "TT-45790",
    platform: "tiktok",
    createdAt: hoursAgo(9),
    customer: "@user_camila_r",
    product: "Faja Shapewear Curve Pro",
    sku: "FTC-SH-014",
    qty: 1,
    status: "pending_logistics",
    location: "Belier",
    shopifyNumber: "#2304",
    invoiceStatus: "ready",
    labelStatus: "missing",
    assignedBy: "Natalie",
    assignedAt: hoursAgo(6),
    activity: [
      { time: hoursAgo(9), text: "Orden importada desde TikTok Shop." },
      { time: hoursAgo(6), text: "Asignada a Belier por Natalie." },
      { time: hoursAgo(6), text: "Ubicación de despacho actualizada en Shopify." },
      { time: hoursAgo(6), text: "Factura generada automáticamente en Odoo." },
    ],
  },
  {
    id: "AMZ-718250",
    platform: "amazon",
    createdAt: hoursAgo(16),
    customer: "L. Fernández",
    product: "Waist Trainer Classic Black",
    sku: "FTC-WT-002",
    qty: 1,
    status: "pending_logistics",
    location: "Norte",
    shopifyNumber: "#2298",
    invoiceStatus: "ready",
    labelStatus: "missing",
    assignedBy: "Diego",
    assignedAt: hoursAgo(10),
    activity: [
      { time: hoursAgo(16), text: "Orden detectada en Shopify (Source: Amazon)." },
      { time: hoursAgo(10), text: "Asignada a Norte por Diego." },
      { time: hoursAgo(10), text: "Ubicación de despacho actualizada en Shopify." },
      { time: hoursAgo(9), text: "Factura generada automáticamente en Odoo." },
    ],
  },

  // ── Attention / error state ────────────────────────────────────────────
  {
    id: "AMZ-717900",
    platform: "amazon",
    createdAt: hoursAgo(27),
    customer: "R. Castillo",
    product: "Faja Post Quirúrgica Etapa 1",
    sku: "FTC-PQ-018",
    qty: 1,
    status: "attention",
    location: "Plaza",
    invoiceStatus: "failed",
    labelStatus: "none",
    assignedBy: "Natalie",
    assignedAt: hoursAgo(25),
    attentionReason: "La automatización falló al generar la factura en Odoo.",
    failedSteps: ["Shopify fulfillment location: OK", "Odoo invoice generation: Failed (timeout)"],
    activity: [
      { time: hoursAgo(27), text: "Orden detectada en Shopify (Source: Amazon)." },
      { time: hoursAgo(25), text: "Asignada a Plaza por Natalie." },
      { time: hoursAgo(25), text: "Ubicación de despacho actualizada en Shopify." },
      { time: hoursAgo(25), text: "Error: no se pudo generar la factura en Odoo (timeout)." },
    ],
  },

  // ── Pending Store (label + invoice ready, waiting for store) ─────────
  {
    id: "TT-45801",
    platform: "tiktok",
    createdAt: hoursAgo(11),
    customer: "@user_paola_m",
    product: "Body Reductor Manga Larga",
    sku: "FTC-BR-009",
    qty: 2,
    status: "pending_store",
    location: "Belier",
    shopifyNumber: "#2301",
    invoiceStatus: "ready",
    labelStatus: "ready",
    labelUrl: "https://ship.pirateship.com/labels/demo-tt45801.pdf",
    assignedBy: "Natalie",
    assignedAt: hoursAgo(8),
    activity: [
      { time: hoursAgo(11), text: "Orden importada desde TikTok Shop." },
      { time: hoursAgo(8), text: "Asignada a Belier por Natalie." },
      { time: hoursAgo(8), text: "Ubicación de despacho actualizada en Shopify." },
      { time: hoursAgo(7), text: "Factura generada automáticamente en Odoo." },
      { time: hoursAgo(3), text: "Label agregado por usuario de Logística." },
    ],
  },
  {
    id: "SHO-3350",
    platform: "shopify",
    createdAt: hoursAgo(15),
    customer: "Karla Vega",
    product: "Faja Shapewear Curve Pro",
    sku: "FTC-SH-014",
    qty: 1,
    status: "pending_store",
    location: "Belier",
    shopifyNumber: "#2299",
    invoiceStatus: "ready",
    labelStatus: "ready",
    labelUrl: "https://ship.pirateship.com/labels/demo-sho3350.pdf",
    assignedBy: "Diego",
    assignedAt: hoursAgo(12),
    activity: [
      { time: hoursAgo(15), text: "Orden online importada desde Shopify." },
      { time: hoursAgo(12), text: "Asignada a Belier por Diego." },
      { time: hoursAgo(12), text: "Ubicación de despacho actualizada en Shopify." },
      { time: hoursAgo(11), text: "Factura generada automáticamente en Odoo." },
      { time: hoursAgo(5), text: "Label agregado por usuario de Logística." },
    ],
  },
  {
    id: "AMZ-718100",
    platform: "amazon",
    createdAt: hoursAgo(18),
    customer: "S. Delgado",
    product: "Waist Trainer Classic Black",
    sku: "FTC-WT-002",
    qty: 1,
    status: "pending_store",
    location: "Norte",
    shopifyNumber: "#2296",
    invoiceStatus: "ready",
    labelStatus: "ready",
    labelUrl: "https://amazon.com/documents/demo-amz718100.pdf",
    assignedBy: "Natalie",
    assignedAt: hoursAgo(13),
    activity: [
      { time: hoursAgo(18), text: "Orden detectada en Shopify (Source: Amazon)." },
      { time: hoursAgo(13), text: "Asignada a Norte por Natalie." },
      { time: hoursAgo(13), text: "Ubicación de despacho actualizada en Shopify." },
      { time: hoursAgo(12), text: "Factura generada automáticamente en Odoo." },
      { time: hoursAgo(6), text: "Documento subido por usuario de Logística." },
    ],
  },

  // ── Colombia (manual) ──────────────────────────────────────────────
  {
    id: "SHO-3402",
    platform: "shopify",
    createdAt: hoursAgo(7),
    customer: "Juliana Prieto",
    product: "Faja Shapewear Curve Pro",
    sku: "FTC-SH-014",
    qty: 1,
    status: "pending_logistics",
    location: "Colombia",
    invoiceStatus: "none",
    labelStatus: "none",
    assignedBy: "Natalie",
    assignedAt: hoursAgo(4),
    activity: [
      { time: hoursAgo(7), text: "Orden online importada desde Shopify." },
      { time: hoursAgo(4), text: "Asignada a Colombia por Natalie." },
      { time: hoursAgo(4), text: "Colombia: factura y label requieren carga manual." },
    ],
  },

  // ── Completed history ──────────────────────────────────────────────
  {
    id: "SHO-3210",
    platform: "shopify",
    createdAt: hoursAgo(72),
    customer: "Mónica Reyes",
    product: "Body Reductor Manga Larga",
    sku: "FTC-BR-009",
    qty: 1,
    status: "completed",
    location: "Plaza",
    shopifyNumber: "#2278",
    invoiceStatus: "ready",
    labelStatus: "ready",
    labelUrl: "https://ship.pirateship.com/labels/demo-sho3210.pdf",
    assignedBy: "Diego",
    assignedAt: hoursAgo(68),
    labelViewedAt: hoursAgo(50),
    invoiceViewedAt: hoursAgo(50),
    completedAt: hoursAgo(49),
    completedBy: "Usuario Plaza",
    activity: [
      { time: hoursAgo(72), text: "Orden online importada desde Shopify." },
      { time: hoursAgo(68), text: "Asignada a Plaza por Diego." },
      { time: hoursAgo(67), text: "Factura generada automáticamente en Odoo." },
      { time: hoursAgo(60), text: "Label agregado por usuario de Logística." },
      { time: hoursAgo(50), text: "Label visto por usuario de Plaza." },
      { time: hoursAgo(50), text: "Factura vista por usuario de Plaza." },
      { time: hoursAgo(49), text: "Orden completada por Usuario Plaza." },
    ],
  },
  {
    id: "TT-45602",
    platform: "tiktok",
    createdAt: hoursAgo(96),
    customer: "@user_gaby.fit",
    product: "Faja Shapewear Curve Pro",
    sku: "FTC-SH-014",
    qty: 1,
    status: "completed",
    location: "Belier",
    shopifyNumber: "#2255",
    invoiceStatus: "ready",
    labelStatus: "ready",
    labelUrl: "https://ship.pirateship.com/labels/demo-tt45602.pdf",
    assignedBy: "Natalie",
    assignedAt: hoursAgo(90),
    labelViewedAt: hoursAgo(80),
    invoiceViewedAt: hoursAgo(80),
    completedAt: hoursAgo(79),
    completedBy: "Usuario Belier",
    activity: [
      { time: hoursAgo(96), text: "Orden importada desde TikTok Shop." },
      { time: hoursAgo(90), text: "Asignada a Belier por Natalie." },
      { time: hoursAgo(89), text: "Factura generada automáticamente en Odoo." },
      { time: hoursAgo(84), text: "Label agregado por usuario de Logística." },
      { time: hoursAgo(80), text: "Label y factura vistos por usuario de Belier." },
      { time: hoursAgo(79), text: "Orden completada por Usuario Belier." },
    ],
  },
  {
    id: "AMZ-717600",
    platform: "amazon",
    createdAt: hoursAgo(120),
    customer: "P. Herrera",
    product: "Waist Trainer Classic Black",
    sku: "FTC-WT-002",
    qty: 3,
    status: "completed",
    location: "Norte",
    shopifyNumber: "#2210",
    invoiceStatus: "ready",
    labelStatus: "ready",
    labelUrl: "https://amazon.com/documents/demo-amz717600.pdf",
    assignedBy: "Diego",
    assignedAt: hoursAgo(115),
    labelViewedAt: hoursAgo(100),
    invoiceViewedAt: hoursAgo(100),
    completedAt: hoursAgo(99),
    completedBy: "Usuario Norte",
    activity: [
      { time: hoursAgo(120), text: "Orden detectada en Shopify (Source: Amazon)." },
      { time: hoursAgo(115), text: "Asignada a Norte por Diego." },
      { time: hoursAgo(114), text: "Factura generada automáticamente en Odoo." },
      { time: hoursAgo(108), text: "Documento subido por usuario de Logística." },
      { time: hoursAgo(100), text: "Label y factura vistos por usuario de Norte." },
      { time: hoursAgo(99), text: "Orden completada por Usuario Norte." },
    ],
  },
];

// Simulates a backend product catalog used for autocomplete when adding an order manually.
export const PRODUCT_CATALOG: { product: string; sku: string }[] = [
  { product: "Faja Shapewear Curve Pro", sku: "FTC-SH-014" },
  { product: "Waist Trainer Classic Black", sku: "FTC-WT-002" },
  { product: "Faja Post Quirúrgica Etapa 1", sku: "FTC-PQ-018" },
  { product: "Faja Post Quirúrgica Etapa 2", sku: "FTC-PQ-021" },
  { product: "Body Reductor Manga Larga", sku: "FTC-BR-009" },
  { product: "Short Moldeador Alta Compresión", sku: "FTC-SM-005" },
  { product: "Fajero Postparto", sku: "FTC-FP-011" },
  { product: "Chaleco Reductor Térmico", sku: "FTC-CR-007" },
];

export const LOCATIONS: { key: string; label: string }[] = [
  { key: "Belier", label: "Belier" },
  { key: "Norte", label: "Norte" },
  { key: "Plaza", label: "Plaza" },
  { key: "Colombia", label: "Colombia" },
];
